#!/bin/bash

# This program is free software. It comes without any warranty, to the extent
# permitted by applicable law. You can redistribute it and/or modify it under
# the terms of the Do What The Fuck You Want To Public License, Version 2, as
# published by Sam Hocevar. See WTFPL.txt or http://www.wtfpl.net/ for more
# details.

shopt -s expand_aliases
alias fail='{ echo $LINENO; exit 1; }'


function main {
  for LINK in $(ls "${SYMTAGDIR}/hashes" | sort -R ); do 

    FILE="$(readlink -m "${SYMTAGDIR}/hashes/${LINK}")";
    echo "${FILE}"

    if ! test -e "${FILE}"; then
      echo "Not found."
      continue
    fi

    echo "Opening:  ${FILE}"
    xterm -e bash -c "while true; do ~/bin/tag -c '${SYMTAGRC}' '${FILE}'; done" &
    KILLME=$!
    run-mailcap --action=view "${FILE}"
    read -p "Hit enter to proceed to the next file.  " response
    unset response
    kill "${KILLME}"

  done
}


SYMTAGRC=~/.symtagrc
SYMTAGDIR=~/.symtag

while test $# -gt 0; do
  case "${1}" in
    -c|--config|--rc)
      SYMTAGRC="${2}"
      shift
      ;;
    -*)
      fail
      ;;
    *)
      fail
      ;;
  esac
  shift
done

if test -f "${SYMTAGRC}"; then
  . "${SYMTAGRC}" || fail
fi

main
