#!/bin/bash

# This program is free software. It comes without any warranty, to the extent
# permitted by applicable law. You can redistribute it and/or modify it under
# the terms of the Do What The Fuck You Want To Public License, Version 2, as
# published by Sam Hocevar. See WTFPL.txt or http://www.wtfpl.net/ for more
# details.

shopt -s expand_aliases
alias fail='{ echo $LINENO; exit 1; }'

SYMTAGRC=~/.symtagrc
SYMTAGDIR=~/.symtag

TARGETS=()
TAGS=()
NAMES=()
while test $# -gt 0; do
  case $1 in
    -f|--file)
      FILES+=($2)
      shift
      ;;
    -n|--name)
      NAMES+=($2)
      ;;
    -t|--tag)
      TAGS+=($2)
      shift
      ;;
    -c|--config|--rc)
      SYMTAGRC=$2
      shift
      ;;
    -*)
      exit 1
      ;;
    *)
      ARGUMENTS+=($1)
      true
      ;;
  esac
  shift
done

test -f $SYMTAGRC && {
  . "${SYMTAGRC}" || fail
}

mkdir -p "${SYMTAGDIR}/"{tags,names,files} || fail

for F in "${FILES[@]}"; do 
  HASH=$(sha256sum "${F}" | { read HASH PATH; echo $HASH; }) || fail
  NAME=$(echo "${F}" | sed 's#^.*/##g') || fail
  NAMES+=($NAME)
  test -e "${SYMTAGDIR}/files/${HASH}" || {
    test -h "${SYMTAGDIR}/files/${HASH}" && {
      rm "${SYMTAGDIR}/files/${HASH}" || fail
    }
    ln -s "$(realpath --relative-to "${SYMTAGDIR}/tags/" "${F}")" "${SYMTAGDIR}/files/${HASH}" || fail
  }
  test -e "${SYMTAGDIR}/names/${NAME}" || {
    test -h "${SYMTAGDIR}/names/${NAME}" && {
      rm "${SYMTAGDIR}/names/${NAME}" || fail
    }
    ln -s "../files/${HASH}" "${SYMTAGDIR}/names/${NAME}" || fail
  }
done
unset HASH

for N in "${NAMES[@]}"; do
  test -h "${SYMTAGDIR}/names/${N}" && {
    HASH=$(readlink "${SYMTAGDIR}/names/${N}" | sed 's#^.*/##g') || fail
    for T in "${TAGS[@]}"; do
      mkdir -p "${SYMTAGDIR}/tags/${T}" || fail
      test -e "${SYMTAGDIR}/tags/${T}/${HASH}" ||
        test -h "${SYMTAGDIR}/tags/${T}/${HASH}" && {
          rm "${SYMTAGDIR}/tags/${T}/${HASH}" || fail
        }
        ln -s "../../files/${HASH}" "${SYMTAGDIR}/tags/${T}/${HASH}" || fail
    done
  }
done
unset HASH
