#!/bin/bash

PATH="$HOME/code/github/abugher/symtag:${PATH}"

test_dir="/tmp/symtag_tests"
symtagdir="${test_dir}/symtagdir"
symtagrc="${test_dir}/symtagrc"

test_count=0
failure_count=0
success_count=0

rm -rf "${test_dir}"
mkdir "${test_dir}"
mkdir "${symtagdir}"
mkdir "${test_dir}/other"
echo SYMTAGDIR="'${symtagdir}'" >> "${symtagrc}"
echo foo > "${test_dir}/foo"
echo bar > "${test_dir}/bar"
echo not_indexed > "${test_dir}/not_indexed"
echo other_foo > "${test_dir}/other/foo"

while read command; do
  let test_count++
  if eval "${command}" >/dev/null 2>&1; then
    #echo "Pass:  ${test_count}"
    let success_count++
  else
    echo "Fail:  ${test_count}"
    let failure_count++
  fi
done < api_tests

echo "Success:  ${success_count}/${test_count}"
echo "Failures: ${failure_count}/${test_count}"
