#!/bin/bash

PATH="$HOME/code/github/abugher/symtag:${PATH}"

test_dir="/tmp/symtag_tests"
symtagdir="${test_dir}/symtagdir"
symtagrc="${test_dir}/symtagrc"

test_count=0
failure_count=0

while read command; do
  let test_count++
  if eval "${command}" >/dev/null 2>&1; then
    echo "Pass:  eval '${command}'"
  else
    echo "Fail:  eval '${command}'"
    let failure_count++
  fi
done << EOF
  readlink -m /dev/null >/dev/null 2>&1
  rm -rf "${test_dir}"
  mkdir "${test_dir}"
  mkdir "${symtagdir}"
  echo SYMTAGDIR="'${symtagdir}'" >> "${symtagrc}"
  symtag -c "${symtagrc}"
  ls -d "${symtagdir}"/{path_by_hash,hash_by_name,hash_by_tag,name_by_hash,tag_by_hash}
  echo foo > "${test_dir}/foo"
  echo bar > "${test_dir}/bar"
  symtag -c "${symtagrc}" "${test_dir}/foo"
  symtag -c "${symtagrc}" "${test_dir}/bar" -t bar
  test '../../foo' == "$(readlink "${symtagdir}/path_by_hash/b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c")"
  test '../../bar' == "$(readlink "${symtagdir}/path_by_hash/7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded97730")"
  symtag -c "${symtagrc}" "${test_dir}"/{foo,bar} -t foobar -t fubar
EOF

echo "Failures (if any):  ${failure_count}/${test_count}"
