#!/bin/bash

PATH="$HOME/code/github/abugher/symtag:${PATH}"

test_dir="/tmp/symtag_tests"
symtagdir="${test_dir}/symtagdir"
symtagrc="${test_dir}/symtagrc"

test_count=0
failure_count=0
success_count=0

while read command; do
  let test_count++
  if eval "${command}" >/dev/null 2>&1; then
    #echo "Pass:  ${test_count}"
    let success_count++
  else
    echo "Fail:  ${test_count}"
    let failure_count++
  fi
done << EOF
  readlink -m /dev/null >/dev/null 2>&1
  rm -rf "${test_dir}"
  mkdir "${test_dir}"
  mkdir "${symtagdir}"
  echo SYMTAGDIR="'${symtagdir}'" >> "${symtagrc}"
  symtag -c "${symtagrc}"
  ls -d "${symtagdir}"/{path_by_hash,hash_by_name,hash_by_tag,name_by_hash,tag_by_hash}
  echo foo > "${test_dir}/foo"
  echo bar > "${test_dir}/bar"
  symtag -c "${symtagrc}" "${test_dir}/foo"
  test '../../foo' == "$(readlink "${symtagdir}/path_by_hash/b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c")"
  test '../path_by_hash/b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c' == "$(readlink "${symtagdir}/hash_by_name/foo")"
  test '../hash_by_name/foo' == "$(readlink "${symtagdir}/name_by_hash/b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c")"
  symtag -c "${symtagrc}" "${test_dir}/bar" -t bar
  test '../../bar' == "$(readlink "${symtagdir}/path_by_hash/7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded97730")"
  test '../path_by_hash/7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded97730' == "$(readlink "${symtagdir}/hash_by_name/bar")"
  test '../hash_by_name/bar' == "$(readlink "${symtagdir}/name_by_hash/7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded97730")"
  test '../../path_by_hash/7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded97730' == "$(readlink "${symtagdir}/hash_by_tag/bar/7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded97730")"
  test '../../hash_by_tag/bar' == "$(readlink "${symtagdir}/tag_by_hash/7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded97730/bar")"
  symtag -c "${symtagrc}" "${test_dir}"/{foo,bar} -t foobar -t fubar
  test '../../path_by_hash/7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded97730' == "$(readlink "${symtagdir}/hash_by_tag/foobar/7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded97730")"
  test '../../path_by_hash/7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded97730' == "$(readlink "${symtagdir}/hash_by_tag/fubar/7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded97730")"
  test '../../hash_by_tag/foobar' == "$(readlink "${symtagdir}/tag_by_hash/7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded97730/foobar")"
  test '../../hash_by_tag/fubar' == "$(readlink "${symtagdir}/tag_by_hash/7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded97730/fubar")"
  test '../../path_by_hash/b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c' == "$(readlink "${symtagdir}/hash_by_tag/foobar/b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c")"
  test '../../path_by_hash/b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c' == "$(readlink "${symtagdir}/hash_by_tag/fubar/b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c")"
  test '../../hash_by_tag/foobar' == "$(readlink "${symtagdir}/tag_by_hash/b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c/foobar")"
  test '../../hash_by_tag/fubar' == "$(readlink "${symtagdir}/tag_by_hash/b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c/fubar")"
EOF

echo "Success:  ${success_count}/${test_count}"
echo "Failures: ${failure_count}/${test_count}"
